version: '2'
services:
  web:
    environment:
     - SHERLOCK_ENV=PROD
    container_name: sherlock
    ports:
     - "80:80"
    image: leogalani/sherlockqa:latest
    depends_on:
      - mysql
  mysql:
    container_name: sherlock-mysql
    restart: always
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'thiswillbechangeonsetupscript'
      MYSQL_DATABASE: 'sherlockdb'
    volumes:
     - ./database:/var/lib/mysql
